version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: larabeatrizms/nginx:prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=node
    networks:
      - node-network

  db_seeder:
    image: mysql:5.7
    volumes:
      - ./db.sql:/db.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=node
    entrypoint:
      [
        "bash",
        "-c",
        "sleep 10 && mysql --user=root --host=db --port=3306 --password=node nodedb < /db.sql && exit",
      ]
    depends_on:
      - db
    networks:
      - node-network

  app:
    build:
      context: .
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- ./start.sh
    networks:
      - node-network
    volumes:
      - ./:/usr/src/app
    tty: true
    depends_on:
      - db

networks:
  node-network:
    driver: bridge
